### ISSUE TITLE
Convert to a static site

### ISSUE THREAD

**Issue by waldyrious** [winniethemu/tiff#10]
It seems to me that the EJS around the code is not really necessary. In particular, there's a single EJS template for the main page (`views/index.ejs`), which  has a single "dynamic" component, the title:

https://github.com/winniethemu/tiff/blob/ee2668324f02dcbf881bca5e6d5173020e8abb4d/views/index.ejs#L4

...which is provided from:

https://github.com/winniethemu/tiff/blob/ee2668324f02dcbf881bca5e6d5173020e8abb4d/routes/index.js#L7

...and could just as well be hardcoded to the `index.ejs` file, which would then be a simple html file that could be served statically (via e.g. GitHub Pages, which would resolve #9).

**Comment by waldyrious** [comment]
Additionally, I wonder if the large number of dependencies (as evidenced by commits 438fd7cc0a67b091a84686dd0537fd4a4f3b62f1 and 87c8749ca5e3d1591bec17e6ac09e5c69ec0d1ee) could not be reduced somehow 🤔 but that's a separate issue.

**Comment by waldyrious** [comment]
Note that you don't actually have to store the project pages in your [winniethemu.github.io repository](https://github.com/winniethemu/winniethemu.github.io) in order to have them appear at https://winniethemu.github.io, and therefore you don't need to archive this repository. By serving the site using GitHub Pages, it will automatically appear at https://winniethemu.github.io, under the path corresponding to the repository name (that is, https://winniethemu.github.io/tiff, exactly as you have it now).

For example, my repo https://github.com/waldyrious/rst-playground is automatically served under  https://waldyrious.github.io/rst-playground just because I activated GitHub pages in the settings:

![image](https://github.com/winniethemu/tiff/assets/478237/423bc7b7-0585-4382-b886-5abc11654a90)

**Comment by winniethemu** [comment]
Oh I see, thanks for the tip! Let me see if I can do that instead.
