### ISSUE TITLE
Moving the site?

### ISSUE THREAD

**Issue by applecuckoo** [winniethemu/tiff#9]
@winniethemu You might have heard but Heroku is discontinuing their free plan. Would you bother moving Tiff to another platform (repl.it, GitHub Pages etc.)?

**Comment by winniethemu** [comment]
Hi, thanks for bringing this up! I've just rewritten this app in React and moved it to my [GitHub Page](https://winniethemu.github.io/tiff). The new source code lives [here](https://github.com/winniethemu/winniethemu.github.io/tree/master/src/pages/tiff), and as a result I'm planning to archive this repo soon.

**Comment by applecuckoo** [comment]
Cool, thanks for porting the site! Closing the issue now.
